### ISSUE TITLE
Where to get a contract code and how to run it?

### ISSUE THREAD

**Issue by gigawarrior** [virtualeconomy/pyvsystems#10]
I've read the Sample Code for Smart Contract in the wiki. In order to run the Smart Contract, I switched the branch to testExecuteContract. However, when running the test_register_contract, I found that the contract_permitted function returned None, which cause the contract None, leading to an error when called the  subsequent register_contract function. Where can I get a template or code of the contract so that I can register then excute it successfully?

**Comment by twwu123** [comment]
You've used the wrong branch for the sample code, the right branch is contractOpt. If you run the sample code in that branch, it should work.
