### ISSUE TITLE
Timeout does not match specified duration

### ISSUE THREAD

**Issue by sunnyking** [virtualeconomy/pyvsystems#24]
pyvsystems 0.2.1, gemmer 0.3.2
Specified timeout of 2 seconds, but actual response is 6 seconds.
Maybe due to an internal logic of retry 3 times?

12-29 09:12:54.738 20801 21043 I python  : [INFO   ] [GemmerTask  ] >>>>>>>502ms>>>>>>> HistoryTask
12-29 09:13:00.936 20801 21043 I python  : [WARNING] [GemmerVnode ] node ping error: NetworkException: Failed to get response: HTTPConnectionPool(host='test.v.systems', port=9922): Max retries exceeded with url: /blocks/height (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76e9765d90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
12-29 09:13:01.256 20801 21043 I python  : [INFO   ] [GemmerVnode ] [http://vnode.vcoin.systems:9924] chosen latency=0.3158128261566162 height=15114060

**Comment by SheldonYS** [comment]
How about change node url from "http://test.v.systems:9922" to "https://test.v.systems/api"? The port 9922 is currently blocked by Cloudflare. 

Here is my test code. It seems the request only try once:

```
import pyvsystems as pv
import time
from pyvsystems import Wrapper, Account, NetworkException


if __name__ == "__main__":
    address = 'AU7nJLcT1mThXGTT1KDkoAtfPzc82Sgay1V'
    chain = pv.testnet_chain(api_wrapper=Wrapper("https://test.v.systems/api", "", timeout=0.5))
    acc = Account(chain=chain, address=address)
    start = int(time.time() * 1000)
    try:
        history = acc.get_tx_history(500, None)
        print("get {} tx records.".format(len(history[0])))
    except NetworkException as ex:
        print("Failed to get HTTP response: {}".format(ex))
    end = int(time.time() * 1000)
    print("Time spend: {} ms".format(end-start))
```
